[package]
name = "rust-lp"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { git = "https://github.com/iced-rs/iced", features = ["image", "advanced"] }
rusqlite = "0.36.0"
quick-xml = "0.38.0"
